### ISSUE TITLE
content-types

### ISSUE THREAD

**Issue by danielsz** [Deraen/ring-cljsjs#1]
Hi! 

It would be nice to add mime-types for common resource types found in cljsjs packages, particularly CSS.

Brower complains for now: 
>Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://localhost:3025/cljsjs/ladda/ladda.min.inc.css".

Are you interested to add this functionality, or would you be interested in a PR?

**Comment by Deraen** [comment]
https://github.com/ring-clojure/ring/blob/1.5.0/ring-core/src/ring/middleware/content_type.clj#L16

There is no reason to duplicate this functionality here as it is already in ring-core.

**Comment by danielsz** [comment]
I hadn't thought about that. Brilliant. Sorry for the noise.
:man_facepalming:
